{
  "previous": "%vyeeIumXOMZWwbrBZKw+txaTWGBgMyEDBiGiYl8Ki0Y=.sha256",
  "author": "@+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519",
  "sequence": 8822,
  "timestamp": 1549405226370,
  "hash": "sha256",
  "content": {
    "type": "post",
    "root": "%UNA62GDuJyRI7DrgcT91lI2s14IHf+ZqQ9+k7CTrSYI=.sha256",
    "branch": "%uokazE2+7kSdPSWRwNfZ8Yv7gVXGwaIeiCaN4MsUOpY=.sha256",
    "channel": "patchfox",
    "text": "Hey [@SoapDog](@gaQw6z30GpfsW9k8V5ED4pHrg8zmrqku24zTSAINhRg=.ed25519), that *does* look super frustrating.\n\nDo you have some code I can run to easily reproduce this? It looks to me like `process.on('uncaughtException'` is likely being redefined somewhere and making it *super* hard to debug.",
    "mentions": [
      {
        "link": "@gaQw6z30GpfsW9k8V5ED4pHrg8zmrqku24zTSAINhRg=.ed25519",
        "name": "SoapDog"
      }
    ]
  },
  "signature": "1a9Mxv0T7q5Q5Ige4tvjP+89qa+SOmZYrQEMtqsdunRr17x+d6L6cOTQYAWn86kfri+UZWhowQ6u0e8vJJOXDA==.sig.ed25519"
}